Repository businext/businext.ai, pull requests merged in 2021-04, with the labels that each got.

#10 Setup graphql server
  docker-compose.yml
  package-lock.json
  package.json
  src/index.ts
  tsconfig.json
Labels: enhancement

#17 Clarify model names
  src/models/data.ts
  src/models/data_models/image.ts
  src/models/data_models/index.ts
  src/models/index.ts
  src/models/insight.ts
Labels: documentation, enhancement

#23 Clean up Dockerfile and package.json
  .dockerignore
  Dockerfile
  docker-compose.yml
  package.json
  src/utils/yelpFusionApiUtils.ts
Labels: enhancement

#24 Create data provider factory
  src/models/data_models/image.ts
  src/providers/data_providers/baseBusinessImageProvider.ts
  src/providers/data_providers/businessImageProviderAggregator.ts
  src/providers/data_providers/mockBusinessImageProvider.ts
  src/providers/data_providers/yelpBusinessImageProvider.ts
  src/utils/yelpFusionApiUtils.ts
Labels: enhancement

#27 Actually implement the word2vec interpretation provider
  src/providers/interpretation_providers/interpretationProvider.ts
  src/providers/interpretation_providers/mockInterpretationProvider.ts
  src/providers/interpretation_providers/word2vecInterpretationProvider.ts
Labels: enhancement

#31 Setup graphql schema
  docker-compose.yml
  package-lock.json
  package.json
  src/graphql/schema/businessInfoInput.graphql
  src/graphql/schema/schema.graphql
  src/index.ts
  tsconfig.json
Labels: enhancement, to do

#29 Move geocode to aggregate level
  src/providers/data_providers/baseBusinessImageProvider.ts
  src/providers/data_providers/businessImageProvider.ts
  src/providers/data_providers/businessImageProviderAggregator.ts
  src/providers/data_providers/mockBusinessImageProvider.ts
  src/providers/data_providers/yelpBusinessImageProvider.ts
Labels: enhancement, to do

#33 Add graphql resolver
  codegen.yml
  package-lock.json
  package.json
  src/graphql/generatedTypes.ts
  src/graphql/resolvers/businessInfoResolver.ts
  src/graphql/resolvers/resolvers.ts
  src/index.ts
Labels: enhancement, to do
